### ISSUE TITLE
Problem with Framework Naming

### ISSUE THREAD

**Issue by srgrr** [Hummingbird-Framework/Hummingbird-Base#1]
Bajo consenso creemos que tu framework debería llamarse HummingBiene porque bende más.

Gracias.

**Comment by mllobet** [comment]
:+1:

**Comment by pnkthrepwood** [comment]
Biene::Vector3

**Comment by Pinkii-** [comment]
++

**Comment by Pinkii-** [comment]
https://github.com/Hummingbird-Framework/Hummingbird-Core/pull/2
